// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwSIX-13O0_8n9M64gEYvZ8abpF9slLc',
    appId: '1:799057153413:web:b95d7c4f73d460543c08ec',
    messagingSenderId: '799057153413',
    projectId: 'codequest-b1390',
    authDomain: 'codequest-b1390.firebaseapp.com',
    databaseURL: 'https://codequest-b1390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codequest-b1390.firebasestorage.app',
    measurementId: 'G-1VH5C3CPWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKpYx9mwUOtXi_G7JKcFNjemlBpJxg44',
    appId: '1:799057153413:android:93561386a9cb14b23c08ec',
    messagingSenderId: '799057153413',
    projectId: 'codequest-b1390',
    databaseURL: 'https://codequest-b1390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codequest-b1390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALyfjofzDJR7vYeIgNqVget-LZUXvczYo',
    appId: '1:799057153413:ios:07e54062be92f5593c08ec',
    messagingSenderId: '799057153413',
    projectId: 'codequest-b1390',
    databaseURL: 'https://codequest-b1390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codequest-b1390.firebasestorage.app',
    iosBundleId: 'com.example.sulamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALyfjofzDJR7vYeIgNqVget-LZUXvczYo',
    appId: '1:799057153413:ios:07e54062be92f5593c08ec',
    messagingSenderId: '799057153413',
    projectId: 'codequest-b1390',
    databaseURL: 'https://codequest-b1390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codequest-b1390.firebasestorage.app',
    iosBundleId: 'com.example.sulamProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpwSIX-13O0_8n9M64gEYvZ8abpF9slLc',
    appId: '1:799057153413:web:9a9fdaef009c60d13c08ec',
    messagingSenderId: '799057153413',
    projectId: 'codequest-b1390',
    authDomain: 'codequest-b1390.firebaseapp.com',
    databaseURL: 'https://codequest-b1390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codequest-b1390.firebasestorage.app',
    measurementId: 'G-LP676NQRP6',
  );
}
